module.exports = [
{
    "name": "Mochica",
    "address": "1469 18th St., San Francisco, CA 94107",
    "hours": "Tuesday - Sunday, 10am - 10pm",
    "price": "$$",
    "cuisine": "Peruvian",
    "rating": 4,
    "img": "https://i.imgur.com/rPMrQoH.png",
    "description": "Mochica spent a decade in the SOMA district of San Francisco, where its innovative cuisine, impressive service and welcoming atmosphere saw the eatery quickly develop a dedicated following.",
    "parking": false,
    "comments": [],
}, 
{
    "name": "Palette Tea House",
    "address": "900 North Point St., Suite B-201A, San Francisco, CA 94109",
    "hours": "Monday - Sunday 11:20am - 7:30pm",
    "price": "$$$",
    "cuisine": "Dim Sum, Cantonese",
    "rating": 4,
    "img": "https://i.imgur.com/btDXbhB.png",
    "description": "The restaurant features vibrant dim sum, authentic wok dishes, and a carefully curated cocktails list.",
    "parking": true,
    "comments": [],
}, 
{
    "name": "Handroll Project",
    "address": "598 Guerrero St San Francisco, CA 94110",
    "hours": "Monday - Sunday, 4pm - 9pm",
    "price": "$$$$$",
    "cuisine": "Japanese",
    "rating": 4,
    "img": "https://i.imgur.com/sQsxIez.png",
    "description": "San Francisco’s first hand roll restaurant, from the team behind Michelin starred, Jū-Ni.",
    "parking": false,
    "comments": [],
}, 
{
    "name": "CA Bakehouse",
    "address": "979 Story Rd Unit 7066 San Jose, CA 95122",
    "hours": "Thursday - Sunday, 12pm - 4pm",
    "price": "$$",
    "cuisine": "Patisserie, Bakery",
    "rating": 5,
    "img": "https://i.imgur.com/zJY7650.png",
    "description": "Enjoy selections from our buttery layered puff dough to the pandan leaves blended to create a creamy custard for our almond choux.",
    "parking": true,
    "comments": [],
}, 
{
    "name": "Kendejah Restaurant",
    "address": "197 Pelton Center Way San Leandro, CA 94577",
    "hours": "Monday - Sunday, 11:30am - 8:30pm",
    "price": "$$",
    "cuisine": "African",
    "rating": 5,
    "img": "https://i.imgur.com/eZXiTDv.png",
    "description": "At Kendejah Restaurant we serve authentic Liberian cuisine. Our entrees include a variety of vegetarian, seafood and meat dishes.",
    "parking": true,
    "comments": [],
}, 
{
    "name": "Teleferic Barcelona",
    "address": "855 El Camino Real Ste 130 Palo Alto, CA 94301",
    "hours": "Monday - Sunday, 11:30am - 9:15pm",
    "price": "$$$",
    "cuisine": "Spanish, Tapas",
    "rating": 4,
    "img": "https://i.imgur.com/V0srlV5.png",
    "description": "Telefèric Barcelona is a family-owned restaurant group in California that serves authentic Spanish tapas, paellas, and innovative cocktails.",
    "parking": true,
    "comments": [],
}, 
{
    "name": "Maggiano's Little Italy",
    "address": "3333 Bristol St Costa Mesa, CA 92626",
    "hours": "Monday - Sunday, 11am - 10pm",
    "price": "$$",
    "cuisine": "Italian",
    "rating": 3,
    "img": "https://i.imgur.com/gu4o9hX.png",
    "description": "Savor the rich flavors of Italian-American dishes inspired by Nonna’s traditional recipes.",
    "parking": true,
    "comments": [],
}, 
{
    "name": "Bacio di Latte",
    "address": "133 Newport Ctr Dr Newport Beach, CA 92660",
    "hours": "Monday - Sunday, 10:30am - 11pm",
    "price": "$$",
    "cuisine": "Gelato",
    "rating": 5,
    "img": "https://i.imgur.com/pD96XZB.png",
    "description": "Bacio di Latte was born in 2011 from Edoardo and Luigi’s passion for gelato, and their desire to share it with the rest of the world.",
    "parking": true,
    "comments": [],
}, 
{
    "name": "TAPS Brewery & Barrel Room",
    "address": "15501 Red Hill Ave Tustin, CA 92780",
    "hours": "Monday - Sunday, 3pm - 9pm",
    "price": "$$",
    "cuisine": "Brewery",
    "rating": 5,
    "img": "https://i.imgur.com/7LG0yPx.png",
    "description": "Enjoy local brews and bar foods.",
    "parking": false,
    "comments": [],
}, 
{
    "name": "Mike's Red Tacos",
    "address": "4310 Genesee Ave Ste 104 San Diego, CA 92117",
    "hours": "Monday - Sunday, 11am - 9:30pm",
    "price": "$$",
    "cuisine": "Tacos",
    "rating": 5,
    "img": "https://i.imgur.com/MOWx17B.png",
    "description": "Our menu is built around our signature Birria tacos, and our famous CrunchStack.  We also have Birria ramen noodle soup, and burritos.",
    "parking": false,
    "comments": [],
}, 
{
    "name": "Snooze, an A.M. Eatery",
    "address": "3940 Fifth Ave San Diego, CA 92103",
    "hours": "Monday - Sunday, 6:30am - 2:30pm",
    "price": "$$",
    "cuisine": "Breakfast & Brunch",
    "rating": 5,
    "img": "https://i.imgur.com/QGw2n6o.png",
    "description": "At Snooze, we believe that breakfast that makes a difference, is different. So we’re turning mornings upside down and turning our communities and planet the right-side up.",
    "parking": false,
    "comments": [],
}, 
]